haxelib.exe set actuate 1.8.9
haxelib.exe set box2d 1.2.3
haxelib.exe set flixel-addons 2.7.4
haxelib.exe set flixel-demos 2.7.0
haxelib.exe set flixel-templates 2.6.0
haxelib.exe set flixel-tools 1.4.4
haxelib.exe set flixel-ui 2.3.2
haxelib.exe set flixel 4.6.0
haxelib.exe set hscript 2.3.0
haxelib.exe set hxcpp 4.0.8
haxelib.exe set layout 1.2.1
haxelib.exe set lime-samples 7.0.0
haxelib.exe set lime 7.3.0
haxelib.exe set openfl-samples 8.7.0
haxelib.exe set openfl 8.9.0
haxelib.exe set systools 1.1.0